FROM alpine:3.21.2 AS base

# Install Requirement Packages
RUN apk update \
    && apk add --no-cache \
    openjdk17

# I put these ENVs for cache the priovious change
ENV MAVEN_VERSION=4.0.0-rc-2
ENV MAVEN_HOME=/usr/lib/mvn
ENV PATH=$MAVEN_HOME/bin:$PATH

RUN wget http://archive.apache.org/dist/maven/maven-4/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz && \
  tar -zxvf apache-maven-$MAVEN_VERSION-bin.tar.gz && \
  rm apache-maven-$MAVEN_VERSION-bin.tar.gz && \
  mv apache-maven-$MAVEN_VERSION /usr/lib/mvn
