apiVersion: v1
kind: Service
metadata:
  name: {{ include "crew.fullname" . }}
  labels:
    {{- include "crew.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      nodePort: {{ .Values.service.nodePort }}
      name: http
  selector:
    {{- include "crew.selectorLabels" . | nindent 4 }}
