name: Build Docker Images

on:
  push:
    branches: [ main ]
    paths:
      - 'base-dockerfiles/**'
      
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile:
          - 'base-dockerfiles/Dockerfile.openjdk17-alpine3.21.2'
          - 'base-dockerfiles/Dockerfile.openjdk17-alpine3.21.2-maven4.0.0'
        include:
          - dockerfile: 'base-dockerfiles/Dockerfile.openjdk17-alpine3.21.2'
            tag: 'jdk17-alp3.21.2'
          - dockerfile: 'base-dockerfiles/Dockerfile.openjdk17-alpine3.21.2-maven4.0.0'
            tag: 'jdk17-alp3.21.2-mvn4'
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Detect changed Dockerfiles
        id: changed-files
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
          echo "::set-output name=changed::$(echo "$CHANGED_FILES" | grep -q "${{ matrix.dockerfile }}" && echo 'true' || echo 'false')"

      - name: Build and Push Docker Image
        if: steps.changed-files.outputs.changed == 'true'
        run: |
          docker buildx build \
            --file ${{ matrix.dockerfile }} \
            --tag hesamrad/crew:${{ matrix.tag }} \
            --push \
            --cache-from type=registry,ref=hesamrad/crew:${{ matrix.tag }} \
            --cache-to type=inline \
            .