name: Build Docker Images

on:
  push:
    branches: [ main ]
    paths:
      - 'base-dockerfiles/**'

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2 

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Detect changed Dockerfiles
        id: changed-files
        run: |
          if git rev-parse --verify HEAD^ > /dev/null 2>&1; then
            CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
          else
            CHANGED_FILES=$(git ls-tree -r HEAD --name-only)
          fi

          CHANGED_DOCKERFILES=$(echo "$CHANGED_FILES" | grep '^base-dockerfiles/Dockerfile')

          # Convert the list of changed Dockerfiles to a JSON array
          echo "::set-output name=changed_dockerfiles::$(echo "$CHANGED_DOCKERFILES" | jq -R -s -c 'split("\n")[:-1]')'

      - name: Build and Push Changed Docker Images
        if: ${{ fromJson(steps.changed-files.outputs.changed_dockerfiles) != '[]' }}
        run: |
          # Loop through each changed Dockerfile
          for DOCKERFILE in ${{ fromJson(steps.changed-files.outputs.changed_dockerfiles) }}; do
            # Extract the tag from the Dockerfile name
            TAG=$(basename "$DOCKERFILE" | sed 's/Dockerfile\.//')

            echo "Building and pushing image for $DOCKERFILE with tag $TAG"
            docker buildx build \
              --file "$DOCKERFILE" \
              --tag hesamrad/crew:$TAG \
              --push \
              --cache-from type=registry,ref=hesamrad/crew:$TAG \
              --cache-to type=inline \
              .
          done