name: Publish Crewmeister Helm Chart

on:
  push:
    branches: [ main ]
    paths:
      - 'helm-chart-crew/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: "v3.10.0"

      - name: Package Helm Chart
        run: |
          helm package ./helm-chart-crew

      - name: Generate Index
        run: |
          mkdir -p helm-repo
          mv helm-chart-crew-*.tgz helm-repo/
          helm repo index helm-repo

      - name: Push to GitHub Pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add helm-repo
          git commit -m "Update Helm chart"
          git push https://${{ secrets.PAT }}@github.com/hesam-rad/infra-devops.git