name: Deploy Mysql with Terraform

on:
  push:
    branches: [ main ]
    paths:
      - 'mysql/**'

jobs:
  deploy-mysql:
    name: Deploy mysql
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0  

      - name: Set up Kubernetes and Helm providers
        run: |
          echo "${{ secrets.KUBECONFIG }}" > mysql/kubeconfig.yaml
          echo "KUBECONFIG=mysql/kubeconfig.yaml" >> $GITHUB_ENV
          
      - name: Terraform Init
        run: |
          cd mysql
          terraform init

      - name: Terraform Plan
        run: |
          cd mysql
          terraform plan

      - name: Terraform Apply
        run: |
          cd mysql
          terraform apply -auto-approve